export interface FhirCode {
  code: string;
  display: string;
  definition?: string;
}

export interface CodeSystemEntry {
  id: string;
  url: string;
  name: string;
  title: string;
  description: string;
  concepts: FhirCode[];
}

export interface ValueSetEntry {
  id: string;
  url: string;
  name: string;
  title: string;
  description: string;
  includes: Array<{ system: string; systemTitle: string; concepts: FhirCode[] }>;
}

export const CODE_SYSTEMS: CodeSystemEntry[] = [
  {
    id: "administrative-gender",
    url: "http://hl7.org/fhir/administrative-gender",
    name: "AdministrativeGender",
    title: "Administrative Gender",
    description: "The gender of a person used for administrative purposes.",
    concepts: [
      { code: "male",    display: "Male",    definition: "Male." },
      { code: "female",  display: "Female",  definition: "Female." },
      { code: "other",   display: "Other",   definition: "Other — not exclusively male or female." },
      { code: "unknown", display: "Unknown", definition: "A proper value is not available." },
    ],
  },
  {
    id: "condition-clinical",
    url: "http://terminology.hl7.org/CodeSystem/condition-clinical",
    name: "ConditionClinicalStatusCodes",
    title: "Condition Clinical Status Codes",
    description: "Preferred value set for Condition.clinicalStatus.",
    concepts: [
      { code: "active",     display: "Active",     definition: "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition." },
      { code: "recurrence", display: "Recurrence", definition: "The subject is experiencing a recurrence of the condition after a period of remission or abatement." },
      { code: "relapse",    display: "Relapse",    definition: "The subject is experiencing a reoccurrence of the condition after a period of remission or abatement." },
      { code: "inactive",   display: "Inactive",   definition: "The subject is no longer experiencing the symptoms of the condition or there is no longer evidence of the condition." },
      { code: "remission",  display: "Remission",  definition: "The subject is no longer experiencing the symptoms of the condition, but there is a risk of the symptoms returning." },
      { code: "resolved",   display: "Resolved",   definition: "The subject is no longer experiencing the symptoms of the condition and there is no perceived risk of the symptoms returning." },
    ],
  },
  {
    id: "observation-category",
    url: "http://terminology.hl7.org/CodeSystem/observation-category",
    name: "ObservationCategoryCodes",
    title: "Observation Category Codes",
    description: "Codes for high-level categorization of Observations.",
    concepts: [
      { code: "vital-signs",  display: "Vital Signs",  definition: "Clinical observations measure the body's basic functions — temperature, pulse, respiration, blood pressure." },
      { code: "laboratory",   display: "Laboratory",   definition: "Observations generated by laboratories. Includes pathology and clinical chemistry." },
      { code: "imaging",      display: "Imaging",      definition: "Observations generated by imaging — radiology, ultrasound, CT, MRI." },
      { code: "procedure",    display: "Procedure",    definition: "Observations generated by clinical procedures." },
      { code: "survey",       display: "Survey",       definition: "Observations generated from questionnaires, assessments, and surveys." },
      { code: "exam",         display: "Exam",         definition: "Observations generated by physical exam findings." },
      { code: "activity",     display: "Activity",     definition: "Observations that measure or record any bodily activity." },
    ],
  },
  {
    id: "fhirsk-identifier-type",
    url: "https://fhir.sk/fhir/CodeSystem/identifier-type",
    name: "FhirSkIdentifierType",
    title: "FHIR.sk Identifier Type",
    description: "Custom CodeSystem for patient identifier types used in FHIR.sk synthetic data.",
    concepts: [
      { code: "nationalId",     display: "National ID",     definition: "Slovak national identifier (rodné číslo). OID: urn:oid:2.16.840.1.113883.2.9.4.3.2" },
      { code: "hospitalNumber", display: "Hospital Number", definition: "Hospital-assigned patient number — local to the institution." },
      { code: "insuranceId",    display: "Insurance ID",    definition: "Health insurance number issued by a Slovak health insurer." },
    ],
  },
];

export const VALUE_SETS: ValueSetEntry[] = [
  {
    id: "administrative-gender",
    url: "http://hl7.org/fhir/ValueSet/administrative-gender",
    name: "AdministrativeGender",
    title: "Administrative Gender",
    description: "The gender of a person used for administrative purposes. Required binding on Patient.gender.",
    includes: [
      {
        system: "http://hl7.org/fhir/administrative-gender",
        systemTitle: "AdministrativeGender",
        concepts: [
          { code: "male",    display: "Male" },
          { code: "female",  display: "Female" },
          { code: "other",   display: "Other" },
          { code: "unknown", display: "Unknown" },
        ],
      },
    ],
  },
  {
    id: "condition-clinical",
    url: "http://terminology.hl7.org/ValueSet/condition-clinical",
    name: "ConditionClinicalStatusCodes",
    title: "Condition Clinical Status Codes",
    description: "Required binding on Condition.clinicalStatus. Must use one of these codes.",
    includes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/condition-clinical",
        systemTitle: "ConditionClinicalStatusCodes",
        concepts: [
          { code: "active" },
          { code: "recurrence" },
          { code: "relapse" },
          { code: "inactive" },
          { code: "remission" },
          { code: "resolved" },
        ].map((c) => ({ ...c, display: c.code.charAt(0).toUpperCase() + c.code.slice(1) })),
      },
    ],
  },
  {
    id: "observation-vital-signs",
    url: "http://hl7.org/fhir/ValueSet/observation-vitalsignresult",
    name: "VitalSigns",
    title: "Vital Signs",
    description: "LOINC codes for vital signs observations. Extensible binding on Observation.code when category = vital-signs.",
    includes: [
      {
        system: "http://loinc.org",
        systemTitle: "LOINC",
        concepts: [
          { code: "8310-5",  display: "Body temperature" },
          { code: "8867-4",  display: "Heart rate" },
          { code: "9279-1",  display: "Respiratory rate" },
          { code: "55284-4", display: "Blood pressure systolic and diastolic" },
          { code: "8480-6",  display: "Systolic blood pressure" },
          { code: "8462-4",  display: "Diastolic blood pressure" },
          { code: "29463-7", display: "Body weight" },
          { code: "8302-2",  display: "Body height" },
          { code: "39156-5", display: "BMI" },
          { code: "59408-5", display: "Oxygen saturation by pulse oximetry" },
          { code: "2708-6",  display: "Oxygen saturation in arterial blood" },
        ],
      },
    ],
  },
  {
    id: "observation-lab-categories",
    url: "http://hl7.org/fhir/ValueSet/observation-category",
    name: "ObservationCategoryCodes",
    title: "Observation Category Codes",
    description: "Codes for high-level categorization of Observation resources. Extensible binding on Observation.category.",
    includes: [
      {
        system: "http://terminology.hl7.org/CodeSystem/observation-category",
        systemTitle: "ObservationCategoryCodes",
        concepts: [
          { code: "vital-signs",  display: "Vital Signs" },
          { code: "laboratory",   display: "Laboratory" },
          { code: "imaging",      display: "Imaging" },
          { code: "procedure",    display: "Procedure" },
          { code: "survey",       display: "Survey" },
          { code: "exam",         display: "Exam" },
          { code: "activity",     display: "Activity" },
        ],
      },
    ],
  },
  {
    id: "fhirsk-identifier-types",
    url: "https://fhir.sk/fhir/ValueSet/identifier-type",
    name: "FhirSkIdentifierTypes",
    title: "FHIR.sk Identifier Types",
    description: "Custom ValueSet for patient identifier types in FHIR.sk synthetic data.",
    includes: [
      {
        system: "https://fhir.sk/fhir/CodeSystem/identifier-type",
        systemTitle: "FhirSkIdentifierType",
        concepts: [
          { code: "nationalId",     display: "National ID" },
          { code: "hospitalNumber", display: "Hospital Number" },
          { code: "insuranceId",    display: "Insurance ID" },
        ],
      },
    ],
  },
];
