export const VERSION = "0.8.0";
export const VERSION_NAME = "Phase 3 — FhirSkPatient Profile";

export const CHANGELOG: { version: string; date: string; changes: string[] }[] = [
  {
    version: "0.8.0",
    date: "2026-06-06",
    changes: [
      "Phase 3 start: FhirSkPatient StructureDefinition (examples/profiles/fhirsk-patient.json)",
      "Profile constraints: identifier 1..*, name 1..*, name.family 1..1, name.given 1..*, gender 1..1, birthDate 1..1, mustSupport on address + communication",
      "Slicing: nationalId slice by system OID (urn:oid:2.16.840.1.113883.2.9.4.3.2)",
      "Validated jana-horvath.json against profile: 0 errors, 1 warning (dom-6 best practice)",
      "Validated invalid Patient against profile: 4 errors (identifier, gender, birthDate, name.given)",
      "docs/phase-3-notes.md: profile structure, $validate usage, all 6 review questions answered",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-06-06",
    changes: [
      "Phase 2 complete — all success criteria met",
      "Transaction Bundle: Patient + Condition + Encounter + MedicationRequest with urn:uuid internal references (examples/bundles/bundle-phase2-clinical.json)",
      "docs/phases.md: Phase 1 + Phase 2 marked complete, Phase 3 set to In Progress",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-06-06",
    changes: [
      "5 Learn articles: Observation, Condition, Encounter, Search, Bundle",
      "/learn/resources rebuilt as article index with 5 cards",
      "Observation: LOINC codes, blood pressure component[], vital-signs vs laboratory",
      "Condition: clinicalStatus + verificationStatus lifecycle, SNOMED CT + ICD-10 coding",
      "Encounter: status lifecycle, class (AMB/EMER/IMP/VR), participant, period, reasonCode",
      "Search: parameter types (string, token, date, reference, quantity), modifiers, searchset Bundle",
      "Bundle: transaction vs batch, urn:uuid internal references, entry structure, atomicity",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-06-06",
    changes: [
      "Reference section: 10 core FHIR entries (FHIR, Resource, Patient, Observation, Bundle, Profile, REST API, Search, Validation, CapabilityStatement)",
      "Reference added to top navigation (Lab | Learn | Reference | About)",
      "Mock Server MVP: 8 static FHIR API routes via Next.js App Router",
      "Mock Server page: endpoint cards with method badge, curl examples",
      "Core clinical synthetic dataset: Condition, Encounter, MedicationRequest, 3 Observations",
      "fhir-mock lib: static FHIR data + searchsetBundle helper + CapabilityStatement",
      "Phase 1 complete: HAPI FHIR local setup, Patient CRUD, Transaction Bundle via curl",
      "docs/phase-1-notes.md: full Phase 1 notes and 7 review questions answered",
      "docs/architecture.md: Reference nav and site map updated",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-06-06",
    changes: [
      "Homepage reduced to 4 sections: Hero, Lab, Learn, Newsletter",
      "Lab modules on homepage: only 3 active (Mock Server, Validator, Synthetic Data)",
      "Removed Future Direction, About and redundant Learning Roadmap sections from homepage",
      "Added Learn Knowledge Tracks section with 6 track links",
      "Updated hero subtitle to reflect interoperability positioning",
      "Updated page metadata description",
      "Added docs/: vision.md, architecture.md, phases.md, design.md",
    ],
  },
  {
    version: "0.3.1",
    date: "2026-06-03",
    changes: [
      "Homepage repositioned as FHIR Interoperability Lab (not a learning platform)",
      "Hero subtitle updated: practical lab identity, removed 'learning environment' framing",
      "Primary CTA: 'Open Lab', secondary CTA: 'Explore Roadmap' → /learn/roadmap",
      "Removed redundant Lab/Learn two-column overview section",
      "Added Learning Roadmap section with direct links",
      "Added Future Direction section: EHDS/EHRxF planned scenarios (no empty pages)",
      "Added About the Project section on homepage",
      "Meta description updated to reflect lab identity",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-06-02",
    changes: [
      "New /newsletter page with topics overview and GitHub fallback",
      "Newsletter CTA section on homepage",
      "Professional 3-column footer (Explore / Connect columns)",
      "About page: updated description (removed 'personal'), added Contact section",
      "Sitemap updated with /newsletter route",
      "siteConfig description updated",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-06-01",
    changes: [
      "Information architecture refactor: Lab / Learn / About navigation",
      "New /lab index with 6 module cards (Resource Builder, Validator, Mock Server, Synthetic Data, Terminology Explorer, Profile Explorer)",
      "New /learn index with 5 learning path cards",
      "Roadmap moved to /learn/roadmap (redirect from /roadmap)",
      "FHIR Foundations moved to /learn/fhir-foundations (redirect from /fhir)",
      "New stub pages: /learn/resources, /learn/profiling, /learn/terminology, /learn/ehds",
      "New lab stub pages for all 6 modules",
      "Reusable components: StatusBadge, ModuleCard, LearningCard, SectionHeader",
      "Homepage refactored: hero + 2-area overview + lab module preview + disclaimer",
      "Sitemap updated with all new routes",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-06-01",
    changes: [
      "Initial project setup",
      "Web: homepage, /fhir, /roadmap, /about, /disclaimer",
      "HAPI FHIR R4 Docker Compose configuration",
      "Synthetic FHIR R4 examples: Patient, Observation, Bundle",
      "Postman collection: Patient CRUD, Bundles",
      "Phase 1 learning notes",
    ],
  },
];
