export const VERSION = "1.6.0";
export const VERSION_NAME = "Hero: Browse Reference CTA removed";

export const CHANGELOG: { version: string; date: string; changes: string[] }[] = [
  {
    version: "1.6.0",
    date: "2026-06-07",
    changes: [
      "Hero: 'Browse Reference' CTA removed — three CTAs reduced to two (Open Lab primary, Learn tertiary text-link)",
    ],
  },
  {
    version: "1.5.9",
    date: "2026-06-07",
    changes: [
      "New page: /copyright — IP acknowledgments for HL7 FHIR R4 (CC0), SNOMED CT (licence required), LOINC (free with attribution), ICD-10/ATC (WHO), UCUM (Regenstrief)",
      "SNOMED CT section highlights Slovakia is not a member country; codes used for educational/synthetic purposes only",
      "Footer: Copyright added to Connect column",
      "Footer bottom bar: third-party terminology notice with link to /copyright",
    ],
  },
  {
    version: "1.5.8",
    date: "2026-06-07",
    changes: [
      "About: maintainer attribution added — Rastislav Mitašík, IT consultant/analyst, independent initiative",
    ],
  },
  {
    version: "1.5.7",
    date: "2026-06-07",
    changes: [
      "Reference: entries grouped into 5 categories with section headings and anchor links (#core-concepts etc.)",
      "Reference: client-side search — filters by title + summary in real time, 'No results' state",
      "Reference: difficulty tags (Beginner / Intermediate / Advanced) on every entry, AND filter with search",
      "Reference: card redesign — left border accent by category, difficulty badge, 'New' badge (<30 days), 'See also' line",
      "Reference: data extracted to lib/reference-data.ts, ReferenceList extracted as client component",
      "page.tsx stays server component — metadata export preserved",
    ],
  },
  {
    version: "1.5.6",
    date: "2026-06-07",
    changes: [
      "New learn track: /learn/slovak — Slovak Interoperability (NCZI, eZdravie, legislative obligations)",
      "Homepage and /learn: 'Health Data Standards' block replaced with 'Slovak Interoperability' → /learn/slovak",
      "/learn/slovak: compliance-timeline as live article, Phase 7–8 articles shown as upcoming stubs",
      "/learn/fhir-foundations: Core Clinical Resources section added (links to Observation, Condition, Encounter, Bundle, Search)",
      "/learn/resources: URL and articles remain accessible, no longer a top-level navigation card",
    ],
  },
  {
    version: "1.5.5",
    date: "2026-06-07",
    changes: [
      "Header: fhir.sk → FHIR.sk (FHIR is an acronym)",
      "Homepage: disclaimer moved from bottom to directly below hero",
      "Homepage: disclaimer text updated — 'Under construction' label, 'under active development' notice added",
    ],
  },
  {
    version: "1.5.4",
    date: "2026-06-07",
    changes: [
      "New article: /learn/ehds/compliance-timeline — EHDS Compliance Timeline for Slovak Healthcare",
      "Covers: GDPR Art. 9 → FHIR Consent/AuditEvent/Provenance, EHDS Phase 1 (2027) datasets, EHDS Phase 2 (2029), Slovak national laws (153/2013, 576/2004, 18/2018)",
      "Includes: overview table (legislation/deadline/FHIR work), 4 technical implications, 8-item compliance checklist",
      "learn/ehds/page.tsx: 3rd article card added, topics list expanded",
    ],
  },
  {
    version: "1.5.3",
    date: "2026-06-07",
    changes: [
      "About: Tech Stack section removed",
      "About: Contact section added — name/email/message form → POST /api/contact → rastislav.mitasik@gmail.com",
      "About: ContactForm extracted as client component (ContactForm.tsx), page stays server component",
      "New API route: POST /api/contact (Resend, subject: Contact — fhir.sk)",
      "HL7 Slovakia removed site-wide: about/page.tsx, disclaimer/page.tsx, page.tsx, learn/fhir-foundations/page.tsx",
    ],
  },
  {
    version: "1.5.2",
    date: "2026-06-07",
    changes: [
      "docs/phases.md: Phase 9 → Architecture Patterns (moved from Phase 10)",
      "docs/phases.md: Phase 10 → Slovak FHIR Profiles (moved from Phase 9)",
      "docs/phases.md: Phase 9 rationale — architecture decisions shape profile constraints, not vice versa",
      "docs/phases.md: Phase 10 profiles now reference Phase 9 architectural context as input",
      "docs/phases.md: knowledge chain updated (Phase 8 → Architecture → Profiles → IG)",
      "docs/phases.md: Learn Track 7 alignment updated to Phase 9",
      "CLAUDE.md: phase table and summary line updated to match new order",
    ],
  },
  {
    version: "1.5.1",
    date: "2026-06-07",
    changes: [
      "docs/phases.md: Phase 7 — eRecept removed, JRUZ as cross-cutting chapter, 3 outputs defined (Analytical docs, MkDocs PoC, eZdravie Examples lab module)",
      "docs/phases.md: Phase 8 — eRecept mapping removed, JRUZ identifiers as cross-cutting section",
      "docs/phases.md: Phase 9 — 8 profiles → 7 profiles, FhirSkMedicationRequest removed",
      "docs/phases.md: Phase 11 — ATC SK ConceptMap removed (eRecept out of scope)",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-06-07",
    changes: [
      "Mock Server: API documentation and curl examples replaced with access request form",
      "Mock Server: name + email + use case form → POST /api/contact-mock → email to rastislav.mitasik@gmail.com",
      "Mock Server: StatusBadge corrected to Live",
      "New API route: POST /api/contact-mock (Resend)",
    ],
  },
  {
    version: "1.4.9",
    date: "2026-06-07",
    changes: [
      "lab/page.tsx: '(Phases 2–4)' removed from live modules note",
      "learn/profiling/conformance: '(Phase 3)' removed from $validate description",
      "learn/profiling/profile: 'Phase 3 learning exercise' rewritten without phase reference",
    ],
  },
  {
    version: "1.4.8",
    date: "2026-06-07",
    changes: [
      "/learn/roadmap: redirects to /learn (page no longer public)",
      "learn/page.tsx: Roadmap card removed, Data Privacy in FHIR card added",
      "learn/page.tsx: metadata and SectionHeader description cleaned (no 'Roadmap' mention)",
      "lab/page.tsx: 'Year 2' → 'a future release', Synthetic Data phase reference removed",
      "lab/synthetic-data, resource-builder, profile-explorer: roadmap links removed → 'planned for a future release'",
      "homepage page.tsx: upcoming logic and Year 2 badge removed, learnAreas simplified",
    ],
  },
  {
    version: "1.4.7",
    date: "2026-06-07",
    changes: [
      "Homepage hero: 'Roadmap →' CTA replaced with 'Learn →' (/learn)",
      "Homepage Learn section: Track 6 'Analytics and Secondary Use' → 'Data Privacy in FHIR' (/learn/privacy)",
      "New page: /learn/privacy — Track 6, GDPR + health data, Consent, AuditEvent, Provenance, Privacy by Design",
    ],
  },
  {
    version: "1.4.6",
    date: "2026-06-07",
    changes: [
      "Header: logo image removed, replaced with fhir.sk text (text-sm font-semibold text-slate-900)",
      "Header: fhir.sk text is HOME button (href=/)",
      "Header: same size and weight as nav links",
    ],
  },
  {
    version: "1.4.5",
    date: "2026-06-07",
    changes: [
      "Header: FHIR.sk text logo replaced with fhir-logo.png image",
      "Header: Phase 1 badge removed",
      "public/fhir-logo.png added",
    ],
  },
  {
    version: "1.4.4",
    date: "2026-06-07",
    changes: [
      "CLAUDE.md: Phase table updated — 5-phase Year 2 structure (Phases 7–11)",
      "docs/phases.md: Phase 7 split — Track A (Current State Analysis) + intro to mapping",
      "Phase 7 Slovak eHealth Analysis: eZdravie architecture, NCZI IM, SOAP/XML/XSD, ADL, číselníky, identifikátory",
      "Phase 8 FHIR Mapping: element-level mapping tables for eLab, eVyšetrenie, eRecept, JRUZ",
      "Phase 9 Slovak FHIR Profiles: 8 profiles derived from Phase 7–8 analysis",
      "Phase 10 Architecture Patterns: Facade/Hybrid/FHIR-native (before IG)",
      "Phase 11 Implementation Guide + Terminology Architecture: FSH/SUSHI + Snowstorm + ConceptMap",
      "Learn Tracks: Track 6 (Phase 7–8), Track 7 (Phase 10), Track 8 (Phase 11), Track 9 (Phase 12+)",
      "Year 3 Phase 12+: EHDS EHRxF conformance, MyHealth@EU cross-border",
    ],
  },
  {
    version: "1.4.3",
    date: "2026-06-07",
    changes: [
      "CLAUDE.md: Phase table updated — Phases 7–10 reflect Slovak Interoperability strategy",
      "docs/phases.md: Phases 7–10 fully defined with success criteria, module priorities and new Year 3 framing",
      "Phase 7: Slovak Interoperability Mapping — eLab, eVyšetrenie, eRecept, JRUZ (priority order)",
      "Phase 8: Slovak FHIR Profiles — derived from Phase 7 analysis, not invented",
      "Phase 9: Architecture Patterns — Facade/Hybrid/FHIR-native decision framework (before IG)",
      "Phase 10: IG + Terminology Architecture — FSH/SUSHI + Snowstorm + ConceptMap (SK→LOINC)",
      "Year 3 framing added: EHDS EHRxF conformance, MyHealth@EU cross-border",
    ],
  },
  {
    version: "1.4.2",
    date: "2026-06-07",
    changes: [
      "Hero badge: 'Mock API · 25 Reference entries · IPS Bundle · EHDS' — specific, not generic",
      "Hero CTAs: 3 buttons — Open Lab (primary), Browse Reference (secondary border), Roadmap (tertiary text-only)",
      "Learn tracks: Track 6 'Analytics and Secondary Use' visually dimmed — dashed border, muted text, Year 2 badge",
    ],
  },
  {
    version: "1.4.1",
    date: "2026-06-07",
    changes: [
      "Homepage: Mock Server, Validator, Terminology Explorer all show Live status (were In Progress / Planned)",
      "Homepage: replace Synthetic Data (stub) with Terminology Explorer in 3-module preview",
      "Homepage: update lab module descriptions to reflect actual capabilities",
      "Homepage: Track 6 link updated to /learn/roadmap with Year 2 note",
      "Lab: Mock Server In Progress → Live, Validator Planned → Live, Terminology Explorer Planned → Live",
      "Lab: reorder modules — 3 Live first, 3 Planned after",
      "Lab: update module descriptions (Validator mentions actual profiles, not ePrescription stub)",
      "Lab: update footer note to reflect 3 live + 3 planned",
      "Roadmap: full rewrite — Phases 1–6 Complete, 7–8 Planned. Correct goals, deliverables and descriptions for each phase.",
      "Roadmap: add Complete status with emerald styling and ✓ badge",
      "Roadmap: subtitle updated from 'Phase 1 is in progress' to 'Phases 1–6 complete'",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-06-07",
    changes: [
      "Phase 6 complete: Governance resources, Mock Server + Validator consolidation, Conformance article",
      "Governance: Consent (GDPR opt-in, provision tree), AuditEvent (DICOM type, IPS access), Provenance (authorship + assembler)",
      "Mock Server: AllergyIntolerance endpoint (GET /api/fhir/AllergyIntolerance), IPS Bundle endpoint (GET /api/fhir/Bundle/[id])",
      "fhir-mock: ALLERGY_INTOLERANCE + IPS_BUNDLE constants, CapabilityStatement updated with 2 new resource types",
      "Validator: AllergyIntolerance profile (fhirsk-allergy) — 4 required checks + criticality warning",
      "ValidatorClient: per-profile valid/invalid samples, new AllergyIntolerance profile option",
      "Learn: What is Conformance — CapabilityStatement, conformance resources table, Consent/AuditEvent/Provenance explained",
      "docs/phases.md: Phase 6 rewritten (Governance + Consolidation, no Analytics PoC), Phase 7 updated to Synthetic Data at Scale",
      "docs/phase-6-notes.md: governance resource elements, conformance vs compliance, 6 review questions",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-06-07",
    changes: [
      "Phase 5 complete: EHDS regulation, IPS Document Bundle, 2 Learn articles",
      "Synthetic IPS Patient Summary (examples/bundles/ips-patient-summary.json): 9 entries, 4 sections, all required IPS sections",
      "AllergyIntolerance resource introduced (examples/patients/allergy-intolerance-example.json): amoxicillin, high criticality, skin rash",
      "Composition resource: document type (60591-5), sections with LOINC codes and narrative text",
      "Learn: FHIR and EHDS — regulation 2025/327, EHRxF timeline, MyHealth@EU, Slovak context, EHDS compliance checklist",
      "Learn: International Patient Summary — document Bundle rules, Composition, required sections table, IPS profiles",
      "/learn/ehds rebuilt as Track 4 article index with 2 articles",
      "docs/phase-5-notes.md: IPS structure, EHDS key facts, AllergyIntolerance elements, 6 review questions",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-06-06",
    changes: [
      "Phase 4 complete: Terminology Explorer MVP, Learn article, ValueSet binding in FhirSkPatient",
      "Terminology Explorer (/lab/terminology-explorer): 5 ValueSets, 4 CodeSystems, tab UI, 2-panel layout",
      "Static terminology data (lib/fhir-terminology.ts): administrative-gender, condition-clinical, observation-category, LOINC vital signs, fhirsk-identifier-type",
      "Learn article: Why Terminologies Matter — CodeSystem, ValueSet, binding strengths, SNOMED vs LOINC",
      "/learn/terminology rebuilt as article index (Track 3)",
      "FhirSkPatient v0.2.0: added required binding on Patient.gender (administrative-gender ValueSet)",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-06-06",
    changes: [
      "Reference expanded from 10 to 25 entries — Phase 3 Reference milestone complete",
      "New entries — Standards: StructureDefinition, Extension, Must-Support, Slicing, Implementation Guide, FHIRPath",
      "New entries — Standards: HL7 v2 (ADT example), CDA (document header example)",
      "New entries — Resources: Condition (SNOMED+ICD-10), Encounter (status lifecycle, class), MedicationRequest (ATC dose example)",
      "New entries — Terminology: ValueSet (binding strengths), CodeSystem (SNOMED/LOINC/ICD-10/ATC/UCUM table)",
      "New entries — Security: SMART on FHIR (launch types, scopes, discovery)",
      "New entries — Core: OperationOutcome (severity table, issue codes)",
      "Reference index reorganized into 5 groups: Core FHIR, Resources, Profiling, Terminology, Security",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-06-06",
    changes: [
      "3 Phase 3 Learn articles under /learn/profiling/",
      "What is a Profile: StructureDefinition, differential vs snapshot, all 6 constraint types, FhirSkPatient table, real-world profiles (IPS, US Core, EHDS)",
      "Validation: 5 validation types, OperationOutcome severity levels, $validate operation, our test results, validation tools",
      "HL7 v2 vs CDA vs FHIR (Track 2): pipe format, CDA XML, FHIR REST, comparison table, coexistence reality",
      "/learn/profiling rebuilt as article index with 3 cards",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-06-06",
    changes: [
      "Validator MVP: /lab/validator — paste FHIR JSON, select profile, get OperationOutcome",
      "API route: POST /api/validate — structural validation + FhirSkPatient profile checks",
      "Profiles supported: base FHIR R4 (structural), fhirsk-patient (cardinality constraints)",
      "UI: textarea, profile selector, load valid/invalid samples, severity color-coding",
      "OperationOutcome displayed with error/warning/information badges and expression paths",
      "Raw OperationOutcome JSON in collapsible details block",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-06-06",
    changes: [
      "Phase 3 start: FhirSkPatient StructureDefinition (examples/profiles/fhirsk-patient.json)",
      "Profile constraints: identifier 1..*, name 1..*, name.family 1..1, name.given 1..*, gender 1..1, birthDate 1..1, mustSupport on address + communication",
      "Slicing: nationalId slice by system OID (urn:oid:2.16.840.1.113883.2.9.4.3.2)",
      "Validated jana-horvath.json against profile: 0 errors, 1 warning (dom-6 best practice)",
      "Validated invalid Patient against profile: 4 errors (identifier, gender, birthDate, name.given)",
      "docs/phase-3-notes.md: profile structure, $validate usage, all 6 review questions answered",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-06-06",
    changes: [
      "Phase 2 complete — all success criteria met",
      "Transaction Bundle: Patient + Condition + Encounter + MedicationRequest with urn:uuid internal references (examples/bundles/bundle-phase2-clinical.json)",
      "docs/phases.md: Phase 1 + Phase 2 marked complete, Phase 3 set to In Progress",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-06-06",
    changes: [
      "5 Learn articles: Observation, Condition, Encounter, Search, Bundle",
      "/learn/resources rebuilt as article index with 5 cards",
      "Observation: LOINC codes, blood pressure component[], vital-signs vs laboratory",
      "Condition: clinicalStatus + verificationStatus lifecycle, SNOMED CT + ICD-10 coding",
      "Encounter: status lifecycle, class (AMB/EMER/IMP/VR), participant, period, reasonCode",
      "Search: parameter types (string, token, date, reference, quantity), modifiers, searchset Bundle",
      "Bundle: transaction vs batch, urn:uuid internal references, entry structure, atomicity",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-06-06",
    changes: [
      "Reference section: 10 core FHIR entries (FHIR, Resource, Patient, Observation, Bundle, Profile, REST API, Search, Validation, CapabilityStatement)",
      "Reference added to top navigation (Lab | Learn | Reference | About)",
      "Mock Server MVP: 8 static FHIR API routes via Next.js App Router",
      "Mock Server page: endpoint cards with method badge, curl examples",
      "Core clinical synthetic dataset: Condition, Encounter, MedicationRequest, 3 Observations",
      "fhir-mock lib: static FHIR data + searchsetBundle helper + CapabilityStatement",
      "Phase 1 complete: HAPI FHIR local setup, Patient CRUD, Transaction Bundle via curl",
      "docs/phase-1-notes.md: full Phase 1 notes and 7 review questions answered",
      "docs/architecture.md: Reference nav and site map updated",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-06-06",
    changes: [
      "Homepage reduced to 4 sections: Hero, Lab, Learn, Newsletter",
      "Lab modules on homepage: only 3 active (Mock Server, Validator, Synthetic Data)",
      "Removed Future Direction, About and redundant Learning Roadmap sections from homepage",
      "Added Learn Knowledge Tracks section with 6 track links",
      "Updated hero subtitle to reflect interoperability positioning",
      "Updated page metadata description",
      "Added docs/: vision.md, architecture.md, phases.md, design.md",
    ],
  },
  {
    version: "0.3.1",
    date: "2026-06-03",
    changes: [
      "Homepage repositioned as FHIR Interoperability Lab (not a learning platform)",
      "Hero subtitle updated: practical lab identity, removed 'learning environment' framing",
      "Primary CTA: 'Open Lab', secondary CTA: 'Explore Roadmap' → /learn/roadmap",
      "Removed redundant Lab/Learn two-column overview section",
      "Added Learning Roadmap section with direct links",
      "Added Future Direction section: EHDS/EHRxF planned scenarios (no empty pages)",
      "Added About the Project section on homepage",
      "Meta description updated to reflect lab identity",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-06-02",
    changes: [
      "New /newsletter page with topics overview and GitHub fallback",
      "Newsletter CTA section on homepage",
      "Professional 3-column footer (Explore / Connect columns)",
      "About page: updated description (removed 'personal'), added Contact section",
      "Sitemap updated with /newsletter route",
      "siteConfig description updated",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-06-01",
    changes: [
      "Information architecture refactor: Lab / Learn / About navigation",
      "New /lab index with 6 module cards (Resource Builder, Validator, Mock Server, Synthetic Data, Terminology Explorer, Profile Explorer)",
      "New /learn index with 5 learning path cards",
      "Roadmap moved to /learn/roadmap (redirect from /roadmap)",
      "FHIR Foundations moved to /learn/fhir-foundations (redirect from /fhir)",
      "New stub pages: /learn/resources, /learn/profiling, /learn/terminology, /learn/ehds",
      "New lab stub pages for all 6 modules",
      "Reusable components: StatusBadge, ModuleCard, LearningCard, SectionHeader",
      "Homepage refactored: hero + 2-area overview + lab module preview + disclaimer",
      "Sitemap updated with all new routes",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-06-01",
    changes: [
      "Initial project setup",
      "Web: homepage, /fhir, /roadmap, /about, /disclaimer",
      "HAPI FHIR R4 Docker Compose configuration",
      "Synthetic FHIR R4 examples: Patient, Observation, Bundle",
      "Postman collection: Patient CRUD, Bundles",
      "Phase 1 learning notes",
    ],
  },
];
