import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "What is a StructureDefinition? — Reference",
  description: "StructureDefinition is the FHIR resource that defines the structure of other resources, data types, extensions, and profiles.",
};

export default function StructureDefinitionReferencePage() {
  return (
    <article className="py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <Link href="/reference" className="text-sm text-slate-500 hover:text-teal-600 transition-colors mb-6 inline-block">← Reference</Link>
        <span className="inline-block text-xs font-semibold text-teal-700 bg-teal-50 px-3 py-1 rounded-full uppercase tracking-widest mb-4">Standards</span>
        <h1 className="text-3xl font-bold text-slate-900 mb-4">What is a StructureDefinition?</h1>
        <p className="text-lg text-slate-600 leading-relaxed mb-6">
          A <strong>StructureDefinition</strong> is the FHIR resource that defines the structure of other resources, data types, extensions, and <Link href="/reference/profile" className="text-teal-600 hover:underline">profiles</Link>. It is both a resource (can be stored on a FHIR server) and a schema (defines what other resources look like).
        </p>

        <div className="border border-slate-200 rounded-xl p-6 mb-8 space-y-3">
          <h2 className="text-sm font-semibold text-slate-700 uppercase tracking-wide">Key fields</h2>
          <ul className="space-y-2 text-sm text-slate-600">
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">url</code> — globally unique canonical identifier for this definition</li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">kind</code> — <code className="font-mono text-xs bg-slate-100 px-1 rounded">resource</code>, <code className="font-mono text-xs bg-slate-100 px-1 rounded">complex-type</code>, <code className="font-mono text-xs bg-slate-100 px-1 rounded">primitive-type</code>, or <code className="font-mono text-xs bg-slate-100 px-1 rounded">logical</code></li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">type</code> — the FHIR type being defined or constrained (e.g. Patient)</li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">baseDefinition</code> — the parent StructureDefinition this one derives from</li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">derivation</code> — <code className="font-mono text-xs bg-slate-100 px-1 rounded">specialization</code> (new type) or <code className="font-mono text-xs bg-slate-100 px-1 rounded">constraint</code> (profile on existing type)</li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">differential</code> — only the elements that differ from the base — what you write</li>
            <li><code className="font-mono text-xs bg-slate-100 px-1 rounded">snapshot</code> — complete element list after merging with base — generated by tooling</li>
          </ul>
        </div>

        <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 mb-8">
          <h2 className="text-sm font-semibold text-slate-700 mb-2">What uses StructureDefinition</h2>
          <ul className="text-sm text-slate-600 space-y-1">
            <li><span className="font-semibold">Resource definitions</span> — every FHIR resource (Patient, Observation…) is defined by a StructureDefinition in the spec</li>
            <li><span className="font-semibold">Profiles</span> — constraints on base resources for specific use cases</li>
            <li><span className="font-semibold">Extensions</span> — definitions of new data elements not in the base spec</li>
            <li><span className="font-semibold">Data types</span> — HumanName, Address, CodeableConcept, Quantity</li>
          </ul>
        </div>

        <div className="border-t border-slate-100 pt-6 flex flex-wrap gap-3 text-sm">
          <span className="text-slate-500">See also:</span>
          <Link href="/reference/profile" className="text-teal-600 hover:underline">Profile</Link>
          <Link href="/reference/extension" className="text-teal-600 hover:underline">Extension</Link>
          <Link href="/reference/slicing" className="text-teal-600 hover:underline">Slicing</Link>
        </div>
      </div>
    </article>
  );
}
