import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "What is a Profile — Profiling and Validation",
  description: "How FHIR profiles constrain base resources using StructureDefinition: cardinality, mustSupport, slicing, bindings, and extensions.",
  alternates: { canonical: "https://fhir.sk/learn/profiling/profile" },
};

export default function ProfileLearnPage() {
  return (
    <article className="py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/learn/profiling" className="text-sm text-slate-500 hover:text-teal-600 transition-colors mb-6 inline-block">
          ← Profiling and Validation
        </Link>

        <div className="mb-12">
          <span className="inline-block text-xs font-semibold text-teal-700 bg-teal-50 px-3 py-1 rounded-full uppercase tracking-widest mb-4">Track 1 — FHIR Fundamentals</span>
          <h1 className="text-3xl sm:text-4xl font-bold text-slate-900">What is a Profile</h1>
          <p className="mt-4 text-lg text-slate-500 leading-relaxed">
            Base FHIR is intentionally loose — almost everything is optional. A Profile is a <code className="font-mono text-sm bg-slate-100 px-1 rounded">StructureDefinition</code> that constrains a base resource for a specific use case, country, or institution.
          </p>
        </div>

        <section className="mb-12">
          <h2 className="text-xl font-bold text-slate-900 mb-4">Why profiles exist</h2>
          <p className="text-slate-700 leading-relaxed mb-4">
            A base FHIR Patient has almost no required fields. <code className="font-mono text-xs bg-slate-100 px-1 rounded">name</code>, <code className="font-mono text-xs bg-slate-100 px-1 rounded">gender</code>, and <code className="font-mono text-xs bg-slate-100 px-1 rounded">birthDate</code> are all optional. This makes the base spec flexible enough for every country and every clinical scenario — but too flexible for any specific implementation.
          </p>
          <p className="text-slate-700 leading-relaxed mb-4">
            A hospital admissions system needs a patient name. An e-prescription system needs a national identifier. A cross-border EU exchange needs a specific identifier format and mandatory language preference. None of that is enforceable by base FHIR alone.
          </p>
          <p className="text-slate-700 leading-relaxed">
            Profiles solve this. They layer additional constraints on top of base FHIR without changing the spec. A resource valid against a profile is automatically valid base FHIR R4 — profiles can only restrict, never expand.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-bold text-slate-900 mb-6">StructureDefinition</h2>
          <p className="text-slate-700 leading-relaxed mb-6">
            A Profile is expressed as a <code className="font-mono text-xs bg-slate-100 px-1 rounded">StructureDefinition</code> resource. The key fields:
          </p>
          <div className="space-y-3 mb-6">
            {[
              { name: "url", detail: "Globally unique identifier for the profile. Used in meta.profile[] to declare that a resource conforms to this profile." },
              { name: "baseDefinition", detail: "The resource or profile being constrained — e.g. http://hl7.org/fhir/StructureDefinition/Patient." },
              { name: "derivation", detail: "constraint (restricts an existing type) or specialization (creates a new type — rare)." },
              { name: "differential", detail: "Only the elements that differ from the base. Shorter and easier to read — this is where you write constraints." },
              { name: "snapshot", detail: "The full element list after merging differential with the base. Generated by tooling, not written by hand." },
            ].map((el) => (
              <div key={el.name} className="border border-slate-200 rounded-lg p-4 text-sm">
                <span className="font-mono text-xs bg-slate-100 px-1 rounded mr-2">{el.name}</span>
                <span className="text-slate-600">{el.detail}</span>
              </div>
            ))}
          </div>

          <div className="bg-slate-800 text-slate-100 rounded-lg p-4 font-mono text-sm overflow-x-auto">
            <div className="text-slate-400 text-xs mb-2">StructureDefinition skeleton</div>
            <pre>{`{
  "resourceType": "StructureDefinition",
  "url": "https://fhir.sk/fhir/StructureDefinition/fhirsk-patient",
  "name": "FhirSkPatient",
  "status": "draft",
  "fhirVersion": "4.0.1",
  "kind": "resource",
  "type": "Patient",
  "baseDefinition": "http://hl7.org/fhir/StructureDefinition/Patient",
  "derivation": "constraint",
  "differential": {
    "element": [ ... ]
  }
}`}</pre>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-bold text-slate-900 mb-6">What a profile can constrain</h2>
          <div className="space-y-4">
            {[
              {
                constraint: "Cardinality",
                example: "Patient.gender: 0..1 → 1..1",
                detail: "Make optional elements required, or restrict repeating elements. You can only increase the minimum or decrease the maximum — never the other way."
              },
              {
                constraint: "mustSupport",
                example: "Patient.address: mustSupport = true",
                detail: "Does not change cardinality. Means: systems claiming conformance to this profile must store and return this element if it is present. The profile author defines what 'support' means in their context."
              },
              {
                constraint: "fixedValue / patternValue",
                example: "identifier.system: fixed = urn:oid:2.16...",
                detail: "Lock an element to a specific value. fixedValue requires exact match. patternValue allows the value to be a superset (used for complex types)."
              },
              {
                constraint: "Binding",
                example: "gender: required binding to AdministrativeGender",
                detail: "Restrict a CodeableConcept or code element to a specific ValueSet. Binding strength: required (must use), extensible (should use), preferred (recommended), example (illustrative only)."
              },
              {
                constraint: "Slicing",
                example: "identifier sliced by system value",
                detail: "Split a repeating element into named sub-types with their own constraints. Discriminator defines how entries are assigned to slices. rules: open allows unrecognised entries; rules: closed rejects them."
              },
              {
                constraint: "Extension",
                example: "Adding birthPlace extension",
                detail: "Add new data elements not present in the base spec. Extensions are defined as separate StructureDefinitions and referenced by URL. Every FHIR element can have extensions."
              },
            ].map((c) => (
              <div key={c.constraint} className="border border-slate-200 rounded-lg p-5">
                <div className="flex items-start justify-between gap-4 mb-2">
                  <h3 className="font-semibold text-slate-900 text-sm">{c.constraint}</h3>
                  <code className="font-mono text-xs bg-teal-50 text-teal-700 px-2 py-0.5 rounded flex-shrink-0">{c.example}</code>
                </div>
                <p className="text-slate-600 text-sm leading-relaxed">{c.detail}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-bold text-slate-900 mb-4">FhirSk Patient — our profile</h2>
          <p className="text-slate-700 leading-relaxed mb-4">
            We built <code className="font-mono text-xs bg-slate-100 px-1 rounded">FhirSkPatient</code> to constrain the base Patient to the minimum set of fields a Slovak healthcare system would need:
          </p>
          <div className="overflow-x-auto border border-slate-200 rounded-lg mb-4">
            <table className="w-full text-sm text-slate-600">
              <thead className="bg-slate-50 text-slate-700 font-semibold border-b border-slate-200">
                <tr>
                  <th className="text-left px-4 py-3">Element</th>
                  <th className="text-left px-4 py-3">Base</th>
                  <th className="text-left px-4 py-3">Profile</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-mono text-xs">
                <tr><td className="px-4 py-3">identifier</td><td className="px-4 py-3 text-slate-400">0..*</td><td className="px-4 py-3 text-teal-700 font-bold">1..*</td></tr>
                <tr><td className="px-4 py-3">name</td><td className="px-4 py-3 text-slate-400">0..*</td><td className="px-4 py-3 text-teal-700 font-bold">1..*</td></tr>
                <tr><td className="px-4 py-3">name.family</td><td className="px-4 py-3 text-slate-400">0..1</td><td className="px-4 py-3 text-teal-700 font-bold">1..1</td></tr>
                <tr><td className="px-4 py-3">name.given</td><td className="px-4 py-3 text-slate-400">0..*</td><td className="px-4 py-3 text-teal-700 font-bold">1..*</td></tr>
                <tr><td className="px-4 py-3">gender</td><td className="px-4 py-3 text-slate-400">0..1</td><td className="px-4 py-3 text-teal-700 font-bold">1..1</td></tr>
                <tr><td className="px-4 py-3">birthDate</td><td className="px-4 py-3 text-slate-400">0..1</td><td className="px-4 py-3 text-teal-700 font-bold">1..1</td></tr>
                <tr><td className="px-4 py-3">address</td><td className="px-4 py-3 text-slate-400">0..*</td><td className="px-4 py-3 font-sans text-slate-600">0..* (mustSupport)</td></tr>
                <tr><td className="px-4 py-3">communication</td><td className="px-4 py-3 text-slate-400">0..*</td><td className="px-4 py-3 font-sans text-slate-600">0..* (mustSupport)</td></tr>
              </tbody>
            </table>
          </div>
          <p className="text-sm text-slate-500">
            Profile file: <code className="font-mono text-xs bg-slate-100 px-1 rounded">examples/profiles/fhirsk-patient.json</code>. Try it in the <Link href="/lab/validator" className="text-teal-600 hover:underline">Validator</Link>.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-xl font-bold text-slate-900 mb-4">Real-world profiles</h2>
          <div className="space-y-3">
            {[
              { name: "International Patient Summary (IPS)", detail: "HL7 global standard for a minimal patient summary. Defines profiles for Patient, AllergyIntolerance, Medication, Condition, and a Composition that bundles them. Used as the basis for EHDS." },
              { name: "US Core", detail: "The US national FHIR profile set, required by the ONC 21st Century Cures Act. Defines must-support elements and US-specific value sets for all major resources." },
              { name: "EHDS EHRxF", detail: "European Health Data Space exchange format. Being developed by the EU as the mandatory cross-border exchange standard. Based on IPS, extended for EU context." },
              { name: "Da Vinci / CARIN", detail: "US payer/provider interoperability IGs for prior authorization, coverage, and claims. Industry-specific profiles built on US Core." },
            ].map((p) => (
              <div key={p.name} className="border border-slate-200 rounded-lg p-4">
                <div className="font-semibold text-slate-800 text-sm mb-1">{p.name}</div>
                <p className="text-slate-600 text-sm leading-relaxed">{p.detail}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="border-t border-slate-200 pt-8">
          <h2 className="text-lg font-bold text-slate-900 mb-4">See also</h2>
          <div className="flex flex-wrap gap-3 text-sm">
            <Link href="/learn/profiling/validation" className="text-teal-600 hover:underline">Learn: Validation</Link>
            <Link href="/reference/profile" className="text-teal-600 hover:underline">Reference: Profile</Link>
            <Link href="/lab/validator" className="text-teal-600 hover:underline">Lab: Validator</Link>
          </div>
        </section>
      </div>
    </article>
  );
}
